In [15]:
from WindPy import w
import numpy as np
import pandas as pd
import datetime
import os
import json
from tqdm import tqdm

w.close()
w.start()
w.isconnected()

Welcome to use Wind Quant API for Python (WindPy)!

COPYRIGHT (C) 2024 WIND INFORMATION CO., LTD. ALL RIGHTS RESERVED.
IN NO CIRCUMSTANCE SHALL WIND BE RESPONSIBLE FOR ANY DAMAGES OR LOSSES CAUSED BY USING WIND QUANT API FOR Python.

True

In [16]:
with open("INDEX_START.json", "r", encoding="utf-8") as f:
    INDEX_START = json.load(f)

In [17]:
df = pd.read_csv("A股指数.csv")
a_share_dict = dict(zip(df["Ticker"], df["Name"]))

df = pd.read_csv("海外指数.csv")
other_market_dict = dict(zip(df["Ticker"], df["Name"]))

print(len(a_share_dict), len(other_market_dict))

332 57

In [18]:
len(INDEX_START)

203

# Load Local Database

In [27]:
INDEX_DATA = {}

for ticker in INDEX_START:
    path = f"Data/{ticker}.csv"
    
    if os.path.isfile(path): 
        data = pd.read_csv(path, index_col = 0, parse_dates = True)
        data.index = pd.to_datetime(data.index, format="%Y-%m-%d", errors='coerce')
        data.index = data.index.date
        INDEX_DATA[ticker] = data.copy(deep = True)
        
len(INDEX_DATA)

186

In [28]:
print(INDEX_DATA['000300.SH'].index[-1])

2025-09-24

# Update Existing Tickers

In [29]:
today = "2025-09-25"
today_date = datetime.datetime.strptime(today, "%Y-%m-%d").date()
today_date

datetime.date(2025, 9, 25)

In [30]:
test_start = "2025-08-30"
temp = w.wsd('HSI.HI', 'pe_ttm,dividendyield2,close', test_start, today, '', usedf = True)[1]
temp.tail()

             PE_TTM  DIVIDENDYIELD2     CLOSE
2025-09-19  12.0401          2.9509  26545.10
2025-09-22  11.9248          2.9940  26344.14
2025-09-23  11.8520          3.0139  26159.12
2025-09-24  11.9948          2.9588  26518.65
2025-09-25  11.9505          2.9615  26484.68

In [31]:
# for ticker in tqdm(INDEX_DATA):
#     data = INDEX_DATA[ticker]

#     idx = -1
#     last = date.index[idx]
#     while not (type(last) is datetime.date):
#         idx -= 1
#         last = date.index[idx]

#     start = (last + pd.Timedelta(days = 1)).strftime("%Y-%m-%d")
    
#     new_data = w.wsd(ticker, 'pe_ttm,dividendyield2,close', start, today, '', usedf = True)[1]

#     if len(new_data) == 1 and new_data.index[0] == ticker:
#         new_data.index = [today_date]
    
#     if new_data.columns[0] == 'OUTMESSAGE':
#         print(ticker)
#         continue
    
#     INDEX_DATA[ticker] = pd.concat([data, new_data])
#     INDEX_DATA[ticker].dropna(inplace = True)

In [32]:
for ticker in tqdm(INDEX_DATA):
    # print("Processing:", ticker)
    data = INDEX_DATA[ticker]

    if data.index[-1] == today_date:
        continue
    
    start = data.index[-1].strftime("%Y-%m-%d")

    new_data = w.wsd(ticker, 'pe_ttm,dividendyield2,close', start, today, '', usedf = True)[1]

    data = pd.concat([data, new_data]).groupby(level = 0).last()
    data.index = pd.to_datetime(data.index, format="%Y-%m-%d", errors='coerce')
    data.index = data.index.date

    data = data[~data.index.duplicated(keep = "last")]

    # if len(new_data) == 1 and new_data.index[0] == ticker:
    #     new_data.index = [today_date]
    
    if new_data.columns[0] == 'OUTMESSAGE':
        print(ticker)
        continue

    INDEX_DATA[ticker] = data.copy(deep = True)
    INDEX_DATA[ticker].dropna(inplace = True)

  0%|                                                                                          | 0/186 [00:00<?, ?it/s]

Processing: NDX.GI

  1%|▍                                                                                 | 1/186 [00:00<01:36,  1.92it/s]

Processing: SPX.GI

  1%|▉                                                                                 | 2/186 [00:01<01:36,  1.91it/s]

Processing: 000913.SH

  2%|█▎                                                                                | 3/186 [00:01<01:35,  1.91it/s]

Processing: 399814.SZ

  2%|█▊                                                                                | 4/186 [00:02<01:35,  1.91it/s]

Processing: 000300.SH

  3%|██▏                                                                               | 5/186 [00:02<01:34,  1.91it/s]

Processing: HSI.HI

  3%|██▋                                                                               | 6/186 [00:03<02:10,  1.38it/s]

Processing: DJSOEP.GI

  4%|███                                                                               | 7/186 [00:04<01:58,  1.51it/s]

Processing: HSTECH.HI

  4%|███▌                                                                              | 8/186 [00:04<01:50,  1.62it/s]

Processing: NDXTMC.GI

  5%|███▉                                                                              | 9/186 [00:05<01:45,  1.68it/s]

Processing: GDAXI.GI

  5%|████▎                                                                            | 10/186 [00:05<01:41,  1.73it/s]

Processing: CSPSADRP.CI

  6%|████▊                                                                            | 11/186 [00:06<01:38,  1.77it/s]

Processing: 830009.XI

  6%|█████▏                                                                           | 12/186 [00:06<01:35,  1.81it/s]

Processing: N225.GI

  7%|█████▋                                                                           | 13/186 [00:07<01:34,  1.84it/s]

Processing: 399975.SZ

  8%|██████                                                                           | 14/186 [00:07<01:32,  1.85it/s]

Processing: 601688.SH

  8%|██████▌                                                                          | 15/186 [00:08<01:31,  1.87it/s]

Processing: HSSCHKY.HI

  9%|██████▉                                                                          | 16/186 [00:09<01:31,  1.87it/s]

Processing: HXC.GI

  9%|███████▍                                                                         | 17/186 [00:09<01:30,  1.86it/s]

Processing: HSHDYI.HI

 10%|███████▊                                                                         | 18/186 [00:10<01:29,  1.87it/s]

Processing: FCHI.GI

 10%|████████▎                                                                        | 19/186 [00:10<01:29,  1.87it/s]

Processing: 931787CNY00.CSI

 11%|████████▋                                                                        | 20/186 [00:11<01:28,  1.88it/s]

Processing: H30533.CSI

 11%|█████████▏                                                                       | 21/186 [00:11<01:27,  1.89it/s]

Processing: HSIII.HI

 12%|█████████▌                                                                       | 22/186 [00:12<01:27,  1.88it/s]

Processing: 931791.CSI

 12%|██████████                                                                       | 23/186 [00:12<01:26,  1.88it/s]

Processing: DJI.GI

 13%|██████████▍                                                                      | 24/186 [00:13<01:26,  1.88it/s]

Processing: 750108.MI

 13%|██████████▉                                                                      | 25/186 [00:13<01:25,  1.88it/s]

Processing: SOX.GI

 14%|███████████▎                                                                     | 26/186 [00:14<01:24,  1.89it/s]

Processing: 122489.MI

 15%|███████████▊                                                                     | 27/186 [00:14<01:25,  1.87it/s]

Processing: HSHKBIO.HI

C:\Users\Bill Yin\AppData\Local\Temp\ipykernel_145924\4281454017.py:12: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, new_data]).groupby(level = 0).last()
 15%|████████████▏                                                                    | 28/186 [00:15<01:25,  1.86it/s]

Processing: HSHCI.HI

 16%|████████████▋                                                                    | 29/186 [00:16<01:41,  1.54it/s]

Processing: RUI.GI

 16%|█████████████                                                                    | 30/186 [00:16<01:36,  1.62it/s]

Processing: SPCLLHCP.SPI

 17%|█████████████▌                                                                   | 31/186 [00:17<01:31,  1.69it/s]

Processing: 707918.MI

 17%|█████████████▉                                                                   | 32/186 [00:17<01:28,  1.74it/s]

Processing: 746059.MI

 18%|██████████████▎                                                                  | 33/186 [00:18<01:26,  1.77it/s]

Processing: 718711L.MI

 18%|██████████████▊                                                                  | 34/186 [00:19<01:25,  1.78it/s]

Processing: 716567.MI

 19%|███████████████▏                                                                 | 35/186 [00:19<01:23,  1.80it/s]

Processing: 704843.MI

 19%|███████████████▋                                                                 | 36/186 [00:20<01:22,  1.83it/s]

Processing: 133333.CSI

 20%|████████████████                                                                 | 37/186 [00:20<01:20,  1.85it/s]

Processing: HSCAIT.HI

 20%|████████████████▌                                                                | 38/186 [00:21<01:19,  1.86it/s]

Processing: HSSCHI.HI

 21%|████████████████▉                                                                | 39/186 [00:21<01:18,  1.87it/s]

Processing: DJCN88.GI

 22%|█████████████████▍                                                               | 40/186 [00:22<01:18,  1.87it/s]

Processing: 707717L.MI

 22%|█████████████████▊                                                               | 41/186 [00:22<01:17,  1.88it/s]

Processing: HSSSHID.HI

 23%|██████████████████▎                                                              | 42/186 [00:23<01:16,  1.89it/s]

Processing: 302400.MI

 23%|██████████████████▋                                                              | 43/186 [00:23<01:15,  1.88it/s]

Processing: HSSSCHD.HI

 24%|███████████████████▏                                                             | 44/186 [00:24<01:16,  1.85it/s]

Processing: HSSI.HI

 24%|███████████████████▌                                                             | 45/186 [00:25<01:29,  1.58it/s]

Processing: CES300.CSI

 25%|████████████████████                                                             | 46/186 [00:25<01:24,  1.66it/s]

Processing: HSCGSI.HI

 25%|████████████████████▍                                                            | 47/186 [00:26<01:21,  1.71it/s]

Processing: HSSCT.HI

 26%|████████████████████▉                                                            | 48/186 [00:26<01:18,  1.76it/s]

Processing: HSMI.HI

 26%|█████████████████████▎                                                           | 49/186 [00:27<01:16,  1.80it/s]

Processing: HSSCNE.HI

 27%|█████████████████████▊                                                           | 50/186 [00:27<01:14,  1.83it/s]

Processing: HSHYLV.HI

 27%|██████████████████████▏                                                          | 51/186 [00:28<01:23,  1.62it/s]

Processing: CESFHY.CSI

 28%|██████████████████████▋                                                          | 52/186 [00:29<01:19,  1.69it/s]

Processing: GPCCH003.FI

 28%|███████████████████████                                                          | 53/186 [00:29<01:16,  1.74it/s]

Processing: HSCSOE.HI

 29%|███████████████████████▌                                                         | 54/186 [00:30<01:13,  1.78it/s]

Processing: HSMCHYI.HI

 30%|███████████████████████▉                                                         | 55/186 [00:30<01:12,  1.81it/s]

Processing: HSSCSOY.HI

 30%|████████████████████████▍                                                        | 56/186 [00:31<01:10,  1.83it/s]

Processing: HSHK35.HI

 31%|████████████████████████▊                                                        | 57/186 [00:31<01:09,  1.85it/s]

Processing: HSBBAC.HI

 31%|█████████████████████████▎                                                       | 58/186 [00:32<01:08,  1.86it/s]

Processing: HSCEI.HI

 32%|█████████████████████████▋                                                       | 59/186 [00:32<01:08,  1.86it/s]

Processing: HSINH.HI

 32%|██████████████████████████▏                                                      | 60/186 [00:33<01:07,  1.88it/s]

Processing: SPHCMSHP.SPI

 33%|██████████████████████████▌                                                      | 61/186 [00:34<01:06,  1.88it/s]

Processing: CES100.CSI

 33%|███████████████████████████                                                      | 62/186 [00:34<01:06,  1.87it/s]

Processing: SPXEWTR.SPI

 34%|███████████████████████████▍                                                     | 63/186 [00:35<01:05,  1.88it/s]

Processing: SPTR500N.SPI

 34%|███████████████████████████▊                                                     | 64/186 [00:35<01:04,  1.88it/s]

Processing: S5INFT.SPI

 35%|████████████████████████████▎                                                    | 65/186 [00:36<01:04,  1.89it/s]

Processing: HSISUI.HI

 35%|████████████████████████████▋                                                    | 66/186 [00:36<01:03,  1.89it/s]

Processing: HSIESGS.HI

 36%|█████████████████████████████▏                                                   | 67/186 [00:37<01:02,  1.89it/s]

Processing: HSFML25.HI

 37%|█████████████████████████████▌                                                   | 68/186 [00:37<01:02,  1.88it/s]

Processing: 990001.CSI

 37%|██████████████████████████████                                                   | 69/186 [00:38<01:02,  1.89it/s]

Processing: 716567.CSI

 38%|██████████████████████████████▍                                                  | 70/186 [00:38<01:01,  1.88it/s]

Processing: 930604.CSI

 38%|██████████████████████████████▉                                                  | 71/186 [00:39<01:01,  1.88it/s]

Processing: h30533.CSI

 39%|███████████████████████████████▎                                                 | 72/186 [00:39<01:00,  1.89it/s]

Processing: 932307.CSI

 39%|███████████████████████████████▊                                                 | 73/186 [00:40<01:00,  1.88it/s]

Processing: 399812.SZ

 40%|████████████████████████████████▏                                                | 74/186 [00:40<00:59,  1.88it/s]

Processing: h30344.CSI

 40%|████████████████████████████████▋                                                | 75/186 [00:41<00:59,  1.87it/s]

Processing: 000815.CSI

 41%|█████████████████████████████████                                                | 76/186 [00:42<00:59,  1.84it/s]

Processing: 000814.SH

 41%|█████████████████████████████████▌                                               | 77/186 [00:42<00:59,  1.84it/s]

Processing: 931238.CSI

 42%|█████████████████████████████████▉                                               | 78/186 [00:43<00:58,  1.85it/s]

Processing: h11057.CSI

 42%|██████████████████████████████████▍                                              | 79/186 [00:43<00:58,  1.84it/s]

Processing: 000805.CSI

 43%|██████████████████████████████████▊                                              | 80/186 [00:44<00:57,  1.86it/s]

Processing: 000961.CSI

 44%|███████████████████████████████████▎                                             | 81/186 [00:44<00:56,  1.87it/s]

Processing: 000811.CSI

 44%|███████████████████████████████████▋                                             | 82/186 [00:45<00:55,  1.88it/s]

Processing: 399804.SZ

 45%|████████████████████████████████████▏                                            | 83/186 [00:45<00:55,  1.86it/s]

Processing: 931239.CSI

 45%|████████████████████████████████████▌                                            | 84/186 [00:46<00:54,  1.87it/s]

Processing: 000901.SH

 46%|█████████████████████████████████████                                            | 85/186 [00:46<00:54,  1.84it/s]

Processing: 930614.CSI

 46%|█████████████████████████████████████▍                                           | 86/186 [00:47<00:54,  1.84it/s]

Processing: 399807.SZ

 47%|█████████████████████████████████████▉                                           | 87/186 [00:47<00:53,  1.86it/s]

Processing: 000827.SH

 47%|██████████████████████████████████████▎                                          | 88/186 [00:48<00:52,  1.87it/s]

Processing: 000812.CSI

 48%|██████████████████████████████████████▊                                          | 89/186 [00:49<00:52,  1.86it/s]

Processing: 930997.CSI

 48%|███████████████████████████████████████▏                                         | 90/186 [00:49<00:51,  1.87it/s]

Processing: 931071.CSI

 49%|███████████████████████████████████████▋                                         | 91/186 [00:50<00:50,  1.88it/s]

Processing: h11054.CSI

 49%|████████████████████████████████████████                                         | 92/186 [00:50<00:50,  1.87it/s]

Processing: 931470.CSI

 50%|████████████████████████████████████████▌                                        | 93/186 [00:51<00:49,  1.88it/s]

Processing: 000813.CSI

 51%|████████████████████████████████████████▉                                        | 94/186 [00:51<00:48,  1.89it/s]

Processing: 931151.CSI

 51%|█████████████████████████████████████████▎                                       | 95/186 [00:52<00:48,  1.89it/s]

Processing: 000964.CSI

 52%|█████████████████████████████████████████▊                                       | 96/186 [00:52<00:47,  1.89it/s]

Processing: 931247.CSI

 52%|██████████████████████████████████████████▏                                      | 97/186 [00:53<00:47,  1.87it/s]

Processing: 931406.CSI

 53%|██████████████████████████████████████████▋                                      | 98/186 [00:53<00:46,  1.88it/s]

Processing: 931152.CSI

 53%|███████████████████████████████████████████                                      | 99/186 [00:54<00:46,  1.89it/s]

Processing: 930598.CSI

 54%|███████████████████████████████████████████                                     | 100/186 [00:54<00:45,  1.89it/s]

Processing: h30372.CSI

 54%|███████████████████████████████████████████▍                                    | 101/186 [00:55<00:44,  1.89it/s]

Processing: 000998.CSI

 55%|███████████████████████████████████████████▊                                    | 102/186 [00:55<00:44,  1.89it/s]

Processing: 930902.CSI

 55%|████████████████████████████████████████████▎                                   | 103/186 [00:56<00:43,  1.89it/s]

Processing: 931409.CSI

 56%|████████████████████████████████████████████▋                                   | 104/186 [00:56<00:43,  1.88it/s]

Processing: 931865.CSI

 56%|█████████████████████████████████████████████▏                                  | 105/186 [00:57<00:42,  1.89it/s]

Processing: h30007.CSI

 57%|█████████████████████████████████████████████▌                                  | 106/186 [00:58<00:42,  1.89it/s]

Processing: 000042.SH

 58%|██████████████████████████████████████████████                                  | 107/186 [00:58<00:47,  1.68it/s]

Processing: 000056.SH

 58%|██████████████████████████████████████████████▍                                 | 108/186 [00:59<00:45,  1.73it/s]

Processing: 399974.SZ

 59%|██████████████████████████████████████████████▉                                 | 109/186 [00:59<00:43,  1.78it/s]

Processing: 931526.CSI

 59%|███████████████████████████████████████████████▎                                | 110/186 [01:00<00:41,  1.82it/s]

Processing: 931802.CSI

 60%|███████████████████████████████████████████████▋                                | 111/186 [01:00<00:40,  1.84it/s]

Processing: h11153.CSI

 60%|████████████████████████████████████████████████▏                               | 112/186 [01:01<00:39,  1.86it/s]

Processing: 931024.CSI

 61%|████████████████████████████████████████████████▌                               | 113/186 [01:01<00:39,  1.87it/s]

Processing: 931027.CSI

 61%|█████████████████████████████████████████████████                               | 114/186 [01:02<00:38,  1.88it/s]

Processing: 931454.CSI

 62%|█████████████████████████████████████████████████▍                              | 115/186 [01:02<00:37,  1.89it/s]

Processing: 931573.CSI

 62%|█████████████████████████████████████████████████▉                              | 116/186 [01:03<00:36,  1.90it/s]

Processing: 931573CNY00.CSI

 63%|██████████████████████████████████████████████████▎                             | 117/186 [01:04<00:36,  1.88it/s]

Processing: 931637.CSI

 63%|██████████████████████████████████████████████████▊                             | 118/186 [01:04<00:36,  1.89it/s]

Processing: h30588.CSI

 64%|███████████████████████████████████████████████████▏                            | 119/186 [01:05<00:35,  1.87it/s]

Processing: h30535.CSI

 65%|███████████████████████████████████████████████████▌                            | 120/186 [01:05<00:35,  1.88it/s]

Processing: h30531.CSI

 65%|████████████████████████████████████████████████████                            | 121/186 [01:06<00:34,  1.88it/s]

Processing: h30202.CSI

 66%|████████████████████████████████████████████████████▍                           | 122/186 [01:06<00:34,  1.88it/s]

Processing: h30178.CSI

 66%|████████████████████████████████████████████████████▉                           | 123/186 [01:07<00:33,  1.89it/s]

Processing: h30035.CSI

 67%|█████████████████████████████████████████████████████▎                          | 124/186 [01:07<00:32,  1.89it/s]

Processing: h30015.CSI

 67%|█████████████████████████████████████████████████████▊                          | 125/186 [01:08<00:32,  1.89it/s]

Processing: 932066.CSI

 68%|██████████████████████████████████████████████████████▏                         | 126/186 [01:08<00:32,  1.84it/s]

Processing: 931892.CSI

 68%|██████████████████████████████████████████████████████▌                         | 127/186 [01:09<00:31,  1.85it/s]

Processing: 931733.CSI

 69%|███████████████████████████████████████████████████████                         | 128/186 [01:09<00:31,  1.83it/s]

Processing: 931484.CSI

 69%|███████████████████████████████████████████████████████▍                        | 129/186 [01:10<00:31,  1.84it/s]

Processing: 931461.CSI

 70%|███████████████████████████████████████████████████████▉                        | 130/186 [01:11<00:30,  1.85it/s]

Processing: 931412.CSI

 70%|████████████████████████████████████████████████████████▎                       | 131/186 [01:11<00:29,  1.86it/s]

Processing: 931380.CSI

 71%|████████████████████████████████████████████████████████▊                       | 132/186 [01:12<00:29,  1.86it/s]

Processing: 931248.CSI

 72%|█████████████████████████████████████████████████████████▏                      | 133/186 [01:12<00:28,  1.86it/s]

Processing: 931160.CSI

 72%|█████████████████████████████████████████████████████████▋                      | 134/186 [01:13<00:27,  1.86it/s]

Processing: 931144.CSI

 73%|██████████████████████████████████████████████████████████                      | 135/186 [01:13<00:27,  1.87it/s]

Processing: 931140.CSI

 73%|██████████████████████████████████████████████████████████▍                     | 136/186 [01:14<00:26,  1.89it/s]

Processing: 931139.CSI

 74%|██████████████████████████████████████████████████████████▉                     | 137/186 [01:14<00:25,  1.89it/s]

Processing: 931079.CSI

 74%|███████████████████████████████████████████████████████████▎                    | 138/186 [01:15<00:25,  1.89it/s]

Processing: 931068.CSI

 75%|███████████████████████████████████████████████████████████▊                    | 139/186 [01:15<00:24,  1.88it/s]

Processing: 931009.CSI

 75%|████████████████████████████████████████████████████████████▏                   | 140/186 [01:16<00:24,  1.89it/s]

Processing: 931008.CSI

 76%|████████████████████████████████████████████████████████████▋                   | 141/186 [01:16<00:23,  1.88it/s]

Processing: 930791.CSI

 76%|█████████████████████████████████████████████████████████████                   | 142/186 [01:17<00:23,  1.88it/s]

Processing: 930653.CSI

 77%|█████████████████████████████████████████████████████████████▌                  | 143/186 [01:17<00:22,  1.89it/s]

Processing: 930648.CSI

 77%|█████████████████████████████████████████████████████████████▉                  | 144/186 [01:18<00:22,  1.89it/s]

Processing: 930632.CSI

 78%|██████████████████████████████████████████████████████████████▎                 | 145/186 [01:18<00:21,  1.88it/s]

Processing: 930608.CSI

 78%|██████████████████████████████████████████████████████████████▊                 | 146/186 [01:19<00:21,  1.88it/s]

Processing: 930606.CSI

 79%|███████████████████████████████████████████████████████████████▏                | 147/186 [01:20<00:20,  1.87it/s]

Processing: 930599.CSI

 80%|███████████████████████████████████████████████████████████████▋                | 148/186 [01:20<00:20,  1.87it/s]

Processing: 399989.SZ

 80%|████████████████████████████████████████████████████████████████                | 149/186 [01:21<00:19,  1.86it/s]

Processing: 399971.SZ

 81%|████████████████████████████████████████████████████████████████▌               | 150/186 [01:21<00:19,  1.86it/s]

Processing: 399967.SZ

 81%|████████████████████████████████████████████████████████████████▉               | 151/186 [01:22<00:18,  1.86it/s]

Processing: 399966.SZ

 82%|█████████████████████████████████████████████████████████████████▍              | 152/186 [01:22<00:18,  1.85it/s]

Processing: 000992.SH

 82%|█████████████████████████████████████████████████████████████████▊              | 153/186 [01:24<00:24,  1.33it/s]

Processing: 000978.CSI

 83%|██████████████████████████████████████████████████████████████████▏             | 154/186 [01:24<00:21,  1.46it/s]

Processing: 000934.SH

 83%|██████████████████████████████████████████████████████████████████▋             | 155/186 [01:25<00:20,  1.54it/s]

Processing: 000914.SH

 84%|███████████████████████████████████████████████████████████████████             | 156/186 [01:25<00:18,  1.63it/s]

Processing: 000806.CSI

 84%|███████████████████████████████████████████████████████████████████▌            | 157/186 [01:26<00:17,  1.68it/s]

Processing: 930928.CSI

 85%|███████████████████████████████████████████████████████████████████▉            | 158/186 [01:26<00:16,  1.72it/s]

Processing: 399959.SZ

 85%|████████████████████████████████████████████████████████████████████▍           | 159/186 [01:27<00:15,  1.77it/s]

Processing: 399809.SZ

 86%|████████████████████████████████████████████████████████████████████▊           | 160/186 [01:27<00:14,  1.81it/s]

Processing: h30263.CSI

 87%|█████████████████████████████████████████████████████████████████████▏          | 161/186 [01:28<00:13,  1.81it/s]

Processing: h30124.CSI

 87%|█████████████████████████████████████████████████████████████████████▋          | 162/186 [01:28<00:13,  1.83it/s]

Processing: 930927.CSI

 88%|██████████████████████████████████████████████████████████████████████          | 163/186 [01:29<00:13,  1.65it/s]

Processing: 931574CNY00.CSI

 88%|██████████████████████████████████████████████████████████████████████▌         | 164/186 [01:30<00:12,  1.72it/s]

Processing: 930709.CSI

 89%|██████████████████████████████████████████████████████████████████████▉         | 165/186 [01:30<00:11,  1.76it/s]

Processing: 930792.CSI

 89%|███████████████████████████████████████████████████████████████████████▍        | 166/186 [01:31<00:11,  1.80it/s]

Processing: 930796.CSI

 90%|███████████████████████████████████████████████████████████████████████▊        | 167/186 [01:31<00:10,  1.83it/s]

Processing: 931456.CSI

 90%|████████████████████████████████████████████████████████████████████████▎       | 168/186 [01:32<00:09,  1.86it/s]

Processing: 930839.CSI

 91%|████████████████████████████████████████████████████████████████████████▋       | 169/186 [01:32<00:09,  1.87it/s]

Processing: 930915.CSI

 91%|█████████████████████████████████████████████████████████████████████████       | 170/186 [01:33<00:08,  1.86it/s]

Processing: 930931.CSI

 92%|█████████████████████████████████████████████████████████████████████████▌      | 171/186 [01:33<00:08,  1.86it/s]

Processing: 930957.CSI

 92%|█████████████████████████████████████████████████████████████████████████▉      | 172/186 [01:34<00:07,  1.87it/s]

Processing: 930965.CSI

 93%|██████████████████████████████████████████████████████████████████████████▍     | 173/186 [01:34<00:06,  1.88it/s]

Processing: 931233.CSI

 94%|██████████████████████████████████████████████████████████████████████████▊     | 174/186 [01:35<00:06,  1.89it/s]

Processing: 931250.CSI

 94%|███████████████████████████████████████████████████████████████████████████▎    | 175/186 [01:35<00:05,  1.85it/s]

Processing: 931722.CSI

 95%|███████████████████████████████████████████████████████████████████████████▋    | 176/186 [01:36<00:05,  1.87it/s]

Processing: 931790.CSI

 95%|████████████████████████████████████████████████████████████████████████████▏   | 177/186 [01:37<00:04,  1.87it/s]

Processing: 987008.CNI

 96%|████████████████████████████████████████████████████████████████████████████▌   | 178/186 [01:37<00:04,  1.87it/s]

Processing: 987016.CNI

 96%|████████████████████████████████████████████████████████████████████████████▉   | 179/186 [01:38<00:03,  1.86it/s]

Processing: 987018.CNI

 97%|█████████████████████████████████████████████████████████████████████████████▍  | 180/186 [01:38<00:03,  1.88it/s]

Processing: h11146.CSI

 97%|█████████████████████████████████████████████████████████████████████████████▊  | 181/186 [01:39<00:02,  1.84it/s]

Processing: h30106.CSI

 98%|██████████████████████████████████████████████████████████████████████████████▎ | 182/186 [01:39<00:02,  1.86it/s]

Processing: h50069CNY10.CSI

 98%|██████████████████████████████████████████████████████████████████████████████▋ | 183/186 [01:40<00:01,  1.86it/s]

Processing: HSIDI.HI

 99%|███████████████████████████████████████████████████████████████████████████████▏| 184/186 [01:40<00:01,  1.87it/s]

Processing: HSISC.HI

 99%|███████████████████████████████████████████████████████████████████████████████▌| 185/186 [01:41<00:00,  1.87it/s]

Processing: TPX.GI

100%|████████████████████████████████████████████████████████████████████████████████| 186/186 [01:41<00:00,  1.83it/s]

In [35]:
data.tail()

             PE_TTM  DIVIDENDYIELD2    CLOSE
2025-09-19  18.3727          2.5740  3147.68
2025-09-22  18.4506          2.5591  3163.17
2025-09-23  18.4506          2.5591  3163.17
2025-09-24  18.4869          2.5541  3170.45
2025-09-25  18.5676          2.5430  3185.35

# Download New Tickers

In [11]:
for ticker, start in tqdm(INDEX_START.items()):
    if ticker in INDEX_DATA:
        continue
        
    assert ticker not in INDEX_DATA
    
    data = w.wsd(ticker, 'pe_ttm,dividendyield2,close', start, today, '', usedf = True)[1]
    
    junk = data['PE_TTM']

    if data.isna().sum().sum() != 0:
        print(ticker)
    
    data.dropna(inplace = True)
    
    INDEX_DATA[ticker] = data.copy(deep = True)

 99%|███████████████████████████████████████▌| 187/189 [00:00<00:00, 270.33it/s]

SP6CSSUP.SPI

100%|█████████████████████████████████████████| 189/189 [00:02<00:00, 84.13it/s]

In [36]:
for ticker, data in INDEX_DATA.items():
    path = os.path.join("Data", f"{ticker}.csv")
    data.to_csv(path, index = True, encoding = "utf-8")

In [16]:
len(INDEX_DATA)

186

In [98]:
INDEX_DATA['931151.CSI'].tail()

                 PE_TTM  DIVIDENDYIELD2      CLOSE
2025-04-23   153.848694          2.4316  1928.0254
2025-04-24   147.197403          2.4611  1905.0281
2025-04-25   333.884491          2.4397  1922.7190
2025-04-28   498.459991          2.4194  1922.8445
2025-04-29  1008.526611          2.4382  1911.9818

In [20]:
temp = w.wsd("NVDA.O", 'close,volume,pe_ttm,mkt_cap_ard', start, today, '', usedf = True)[1]

In [21]:
temp.tail()

             CLOSE       VOLUME     PE_TTM   MKT_CAP_ARD
2025-08-14  182.02  129553959.0  57.848854  4.441288e+12
2025-08-15  180.45  156602161.0  57.349884  4.402980e+12
2025-08-18  182.01  132007959.0  57.845676  4.441044e+12
2025-08-19  175.64  185229219.0  55.821190  4.285616e+12
2025-08-20  175.64          NaN  55.821190  4.285616e+12

In [82]:
temp = INDEX_DATA['000300.SH']

temp.tail(30)

             PE_TTM  DIVIDENDYIELD2      CLOSE
2025-06-20  12.8262          3.2117  3846.6443
2025-06-23  12.9015          3.1666  3857.9016
2025-06-24  13.0251          3.1389  3904.0342
2025-06-25  13.1709          3.2288  3960.0662
2025-06-26  13.1643          3.3321  3946.0195
2025-06-27  13.0224          3.3039  3921.7578
2025-06-30  13.0659          3.2316  3936.0791
2025-07-01  13.1154          3.2264  3942.7620
2025-07-02  13.1225          3.2248  3943.6849
2025-07-03  13.1583          3.2269  3968.0676
2025-07-04  13.2300          3.2043  3982.2034
2025-07-07  13.1866          3.2766  3965.1746
2025-07-08  13.2629          3.2540  3998.4527
2025-07-09  13.2667          3.1696  3991.4006
2025-07-10  13.3386          3.1578  4010.0243
2025-07-11  13.3089          3.1741  4014.8070
2025-07-14  13.3252          2.9967  4017.6678
2025-07-15  13.3163          3.0118  4019.0644
2025-07-16  13.2862          3.0607  4007.2019
2025-07-17  13.3168          2.9327  4034.4910
2025-07-18  13.3872          2.9132  4058.5486
2025-07-21  13.4486          2.8229  4085.6072
2025-07-22  13.5284          2.8199  4118.9582
2025-07-23  13.5425          2.8199  4119.7685
2025-07-24  13.5888          2.7982  4149.0368
2025-07-25  13.5069          2.8256  4127.1634
2025-07-28  13.5171          2.7732  4135.8242
2025-07-29  13.3536          2.7739  4152.0247
2025-07-30  13.3930          2.7597  4151.2379
2025-07-31  13.1865          2.8239  4075.5912